version: '3'

#networks:
#  services:
#    ipam:
#      config:
#        - subnet: 173.17.0.0/24

services:
  #
  # Pool
  #
  #pool:
  #  build:
  #    context: .
  #    dockerfile: indy-pool.dockerfile
  #    args:
  #      - pool_ip=173.17.0.100
  #  ports:
  #    - 9701-9708:9701-9708
  #  networks:
  #    services:
  #      ipv4_address: 173.17.0.100

  #
  # Agents
  #
  alice:
    image: indy-agentjs
    build:
      context: .
    command: "bash -c 'npm start'"
    environment:
      - PORT=3000
      - NAME=Alice
      - EMAIL=alice@faber.edu
      - PASSWORD=123
      - USERNAME=alice
      - PUBLIC_DID_ENDPOINT=173.17.0.150:3000
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3000:3000
    #depends_on:
      #- pool
    networks:
      services:
        ipv4_address: 173.17.0.150

  #
  #
  bob:
    image: indy-agentjs
    command: "bash -c 'npm start'"
    environment:
      - PORT=3001
      - NAME=Bob
      - EMAIL=bob@byu.edu
      - PASSWORD=123
      - USERNAME=bob
      - PUBLIC_DID_ENDPOINT=173.17.0.160:3001
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3001:3001
    depends_on:
      #- pool
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.160

  faber:
    image: indy-agentjs
    command: "bash -c 'npm start'"
    environment:
      - PORT=3002
      - NAME=Faber University
      - EMAIL=admin@faber.edu
      - PASSWORD=123
      - USERNAME=faber
      - PUBLIC_DID_ENDPOINT=173.17.0.170:3002
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3002:3002
    depends_on:
      #- pool
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.170

  acme:
    image: indy-agentjs
    command: "bash -c 'npm start'"
    environment:
      - PORT=3003
      - NAME=Acme Corporation
      - EMAIL=boss@acme.com
      - PASSWORD=123
      - USERNAME=acme
      - PUBLIC_DID_ENDPOINT=173.17.0.180:3003
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3003:3003
    depends_on:
      #- pool
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.180

  thrift:
    image: indy-agentjs
    command: "bash -c 'npm start'"
    environment:
      - PORT=3004
      - NAME=Thrift Bank
      - EMAIL=owner@thrift.com
      - PASSWORD=123
      - USERNAME=thrift
      - PUBLIC_DID_ENDPOINT=173.17.0.190:3004
      - DOCKERHOST=${DOCKERHOST}
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3004:3004
    depends_on:
      #- pool
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.190
